### ISSUE TITLE
Complete pip/conda list on desktop and laptop versions?

### ISSUE THREAD

**Issue by pieris98** [sunhan1997/IndusGrasp#7]
Hey again @sunhan1997 
I'm still trying to test the code and it doesn't work because of incompatibilities with various libraries.

This is what I've installed so far because of errors I got trying to run `python test.py`:

`python==3.8.19` (still have to try 3.7 for cython 0.29 to work without building wheel)
`cython==0.29` (only way to be able to install `cyglfw3` for dataset preparation/rendering)
`cyglfw3==3.1.2.0`
`open3d` (I didn't specify version, which one is used in your code??)
`graspnetAPI` (I didn't specify version, which one is used in your code??)

`numpy`: downgraded from 1.24.4 to 1.20.3 (used 1.20.3 because it was the ONLY available version of numpy that's compatible with `pandas`, otherwise `pip` complains in many versions of `pandas` even when using the older `pandas==1.5.3` that it needs `numpy>=1.20.3`)
----->This leads me to my current ERROR caused in numpy typing now

AttributeError: module 'numpy.typing' has no attribute 'NDArray'

Traceback:
```
Traceback (most recent call last):
  File "test.py", line 289, in <module>
    from dataset import gen_multi_feature_fusion_map
  File "/home/cherry/dev/IndusGrasp/dataset.py", line 10, in <module>
    from torchvision import transforms
  File "/home/cherry/miniconda/envs/indus/lib/python3.8/site-packages/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/home/cherry/miniconda/envs/indus/lib/python3.8/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from .lsun import LSUN, LSUNClass
  File "/home/cherry/miniconda/envs/indus/lib/python3.8/site-packages/torchvision/datasets/lsun.py", line 2, in <module>
    from PIL import Image
  File "/home/cherry/miniconda/envs/indus/lib/python3.8/site-packages/PIL/Image.py", line 68, in <module>
    from ._typing import StrOrBytesPath, TypeGuard
  File "/home/cherry/miniconda/envs/indus/lib/python3.8/site-packages/PIL/_typing.py", line 10, in <module>
    NumpyArray = npt.NDArray[Any]
AttributeError: module 'numpy.typing' has no attribute 'NDArray'
```

This is my current `pip list` output:
```
Package                   Version
------------------------- -----------
addict                    2.4.0
asttokens                 2.4.1
attrs                     24.2.0
autolab-core              1.1.1
autolab-perception        1.0.0
backcall                  0.2.0
blinker                   1.8.2
certifi                   2024.8.30
charset-normalizer        3.3.2
click                     8.1.7
colorlog                  6.8.2
comm                      0.2.2
ConfigArgParse            1.7
contourpy                 1.1.1
cvxopt                    1.3.2
cycler                    0.12.1
cyglfw3                   3.1.0.2
Cython                    0.29
dash                      2.18.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
decorator                 5.1.1
dill                      0.3.8
executing                 2.1.0
fastjsonschema            2.20.0
ffmpeg-python             0.2.0
Flask                     3.0.3
fonttools                 4.53.1
future                    1.0.0
grasp_nms                 1.0.2
graspnetAPI               1.2.11
h5py                      3.11.0
idna                      3.8
imageio                   2.35.1
imgaug                    0.4.0
importlib_metadata        8.5.0
importlib_resources       6.4.5
ipython                   8.12.3
ipywidgets                8.1.5
itsdangerous              2.2.0
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter_core              5.7.2
jupyterlab_widgets        3.0.13
kiwisolver                1.4.7
lazy_loader               0.4
MarkupSafe                2.1.5
matplotlib                3.7.5
matplotlib-inline         0.1.7
multiprocess              0.70.16
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.1
numpy                     1.20.3
open3d                    0.18.0
opencv-contrib-python     4.1.2.30
opencv-python             4.1.2.30
packaging                 24.1
pandas                    2.0.3
parso                     0.8.4
pexpect                   4.9.0
pickleshare               0.7.5
pillow                    10.4.0
pip                       24.2
pkgutil_resolve_name      1.3.10
platformdirs              4.3.2
plotly                    5.24.1
progressbar               2.5
prompt_toolkit            3.0.47
ptyprocess                0.7.0
pure_eval                 0.2.3
pyassimp                  3.3
Pygments                  2.18.0
PyOpenGL                  3.1.5
PyOpenGL-accelerate       3.1.5
pyparsing                 3.1.4
pypng                     0.0.21
pyquaternion              0.9.9
pyserial                  3.5
python-dateutil           2.9.0.post0
pytz                      2024.2
PyWavefront               1.3.3
PyWavelets                1.4.1
PyYAML                    6.0.2
referencing               0.35.1
requests                  2.32.3
retrying                  1.3.4
rpds-py                   0.20.0
ruamel.yaml               0.18.6
ruamel.yaml.clib          0.2.8
scikit-image              0.19.3
scikit-learn              1.3.2
scipy                     1.10.1
setproctitle              1.3.3
setuptools                73.0.1
shapely                   2.0.6
six                       1.16.0
stack-data                0.6.3
tenacity                  9.0.0
threadpoolctl             3.5.0
tifffile                  2023.7.10
torch                     1.5.0
torchvision               0.6.0
tqdm                      4.66.5
traitlets                 5.14.3
transforms3d              0.3.1
trimesh                   4.4.9
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.3
wcwidth                   0.2.13
Werkzeug                  3.0.4
wheel                     0.44.0
widgetsnbextension        4.0.13
zipp                      3.20.1

```

And this is my `conda list` (I used conda):
```
# packages in environment at /home/cherry/miniconda/envs/indus:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
addict                    2.4.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
autolab-core              1.1.1                    pypi_0    pypi
autolab-perception        1.0.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2024.8.30                pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorlog                  6.8.2                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cvxopt                    1.3.2                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cyglfw3                   3.1.0.2                  pypi_0    pypi
cython                    0.29                     pypi_0    pypi
dash                      2.18.1                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
executing                 2.1.0                    pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
glfw3                     3.2.1                         0    https://anaconda.org/menpo/glfw3/3.2.1/download
grasp-nms                 1.0.2                    pypi_0    pypi
graspnetapi               1.2.11                   pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
idna                      3.8                      pypi_0    pypi
imageio                   2.35.1                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.5                  he02047a_1    conda-forge
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
numpy                     1.20.3                   pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
opencv-contrib-python     4.1.2.30                 pypi_0    pypi
opencv-python             4.1.2.30                 pypi_0    pypi
openssl                   3.3.2                hb9d3cd8_0    conda-forge
packaging                 24.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2               pyh8b19718_1    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.3.2                    pypi_0    pypi
plotly                    5.24.1                   pypi_0    pypi
progressbar               2.5                      pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pyassimp                  3.3                      pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyopengl                  3.1.5                    pypi_0    pypi
pyopengl-accelerate       3.1.5                    pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pypng                     0.0.21                   pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyserial                  3.5                      pypi_0    pypi
python                    3.8.19          hd12c33a_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pywavefront               1.3.3                    pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                73.0.1             pyhd8ed1ab_0    conda-forge
shapely                   2.0.6                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
tenacity                  9.0.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torch                     1.5.0                    pypi_0    pypi
torchvision               0.6.0                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
transforms3d              0.3.1                    pypi_0    pypi
trimesh                   4.4.9                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.3                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.13                   pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.20.1                   pypi_0    pypi
```
Can you please provide your `pip list`/`conda list` of your laptop and desktop so that I can try a working environment? Anyone else who got the simple `python test` to work please feel free to share your environment.

Thanks again for all your help.

**Comment by sunhan1997** [comment]
I'm sorry, I did this work with GTX 1650. Therefore, it may not be able to render on RTX 40/30.  

name: yolo
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ca-certificates=2021.10.8=ha878542_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_16
  - libgomp=11.2.0=h1d223b6_16
  - libnsl=2.0.0=h7f98852_0
  - libstdcxx-ng=11.2.0=he4da1e4_16
  - libzlib=1.2.11=h166bdaf_1014
  - ncurses=6.3=h27087fc_1
  - openssl=1.1.1o=h166bdaf_0
  - pip=21.3.1=pyhd8ed1ab_0
  - python=3.6.15=hb7a2778_0_cpython
  - python_abi=3.6=2_cp36m
  - readline=8.1=h46c0cb4_0
  - setuptools=58.0.4=py36h5fab9bb_2
  - sqlite=3.38.5=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - pip:
    - actionlib==1.12.1
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - angles==1.9.12
    - apptools==5.1.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-generator==1.10
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.4.0
    - backcall==0.2.0
    - bleach==4.1.0
    - blobfile==0.11.0
    - bondpy==1.8.5
    - cached-property==1.5.2
    - camera_calibration==1.15.0
    - camera_calibration_parsers==1.11.13
    - catkin==0.7.29
    - certifi==2022.5.18.1
    - cffi==1.15.0
    - chardet==4.0.0
    - charset-normalizer==2.0.12
    - configobj==5.0.6
    - controller_manager==0.18.4
    - controller_manager_msgs==0.18.4
    - cv_bridge==1.13.0
    - cvxopt==1.3.0
    - cycler==0.10.0
    - cyglfw3==3.1.0.2
    - cython==0.29.24
    - dataclasses==0.8
    - decorator==4.4.2
    - defusedxml==0.7.1
    - diagnostic_analysis==1.9.7
    - diagnostic_common_diagnostics==1.9.7
    - diagnostic_updater==1.9.7
    - dynamic_reconfigure==1.6.4
    #- easy-dexnet==0.1.0
    - easydict==1.9
    - ecos==2.0.10
    - einops==0.4.1
    - entrypoints==0.4
    - envisage==6.0.1
    - filelock==3.4.1
    #- freetype-py==2.3.0
    - frozenlist==1.2.0
    - fvcore==0.1.5.post20220512
    - gazebo_plugins==2.8.7
    - gazebo_ros==2.8.7
    - gencpp==0.6.5
    - geneus==2.2.6
    - genlisp==0.4.16
    - genmsg==0.5.16
    - gennodejs==2.0.1
    - genpy==0.6.16
    - h5py==3.1.0
    - idna==3.3
    - idna-ssl==1.1.0
    - image_geometry==1.13.0
    - imageio==2.9.0
    - imgaug==0.4.0
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - interactive-markers==1.11.5
    - iopath==0.1.9
    - ipykernel==5.5.6
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.17.2
    - jinja2==3.0.3
    - joblib==1.1.0
    - joint_state_publisher==1.12.15
    - joint_state_publisher_gui==1.12.15
    - json-tricks==3.15.5
    - jsonschema==3.2.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - kdl-parser-py==1.13.3
    - kiwisolver==1.3.1
    - laser_geometry==1.6.7
    - llvmlite==0.36.0
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - mayavi==4.7.4
    - message_filters==1.14.13
    - mistune==0.8.4
    - mmcv==1.4.4
    - moveit-core==1.0.10
    - moveit_commander==1.0.10
    - moveit_ros_planning_interface==1.0.10
    - moveit_ros_visualization==1.0.10
    - multidict==5.2.0
    - mypy==0.960
    - mypy-extensions==0.4.3
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.5
    - networkx==2.5.1
    - nose==1.3.7
    - notebook==6.4.10
    - numba==0.53.1
    - numpy==1.19.5
    - open3d==0.12.0
    - opencv-contrib-python==4.5.5.64
    - opencv-python==4.5.5.64
    - osqp==0.6.2.post5
    - packaging==21.3
    - pandas==1.1.5
    - pandocfilters==1.5.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pluggy==1.0.0
    - plyfile==0.7.4
    - portalocker==2.4.0
    - progressbar==2.5
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==4.21.0
    - ptyprocess==0.7.0
    - py==1.11.0
    - pyassimp==4.1.4
    - pycocotools==2.0.4
    - pycparser==2.21
    - pycryptodomex==3.14.1
    - pyface==7.4.1
    - pyglet==2.0a4
    - pygments==2.12.0
    - pyhull==2015.2.1
    - pykdtree==1.3.4
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
    - pyparsing==2.4.7
    - pypng==0.0.21
    - pyquaternion==0.9.9
    - pyrealsense2==2.50.0.3812
    - pyrender==0.1.45
    - pyrsistent==0.18.0
    - pytest==7.0.1
    - python-dateutil==2.8.2
    - python-utils==2.5.6
    - python_qt_binding==0.4.4
    - pytz==2022.1
    - pywavelets==1.1.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qdldl==0.1.5.post2
    - qt-dotgraph==0.4.2
    - qt-gui==0.4.2
    - qt-gui-cpp==0.4.2
    - qt-gui-py-common==0.4.2
    - qt_create==0.2.10
    - requests==2.27.1
    - resnest==0.0.6b20220603
    - resource_retriever==1.12.7
    - rosbag==1.14.13
    - rosboost-cfg==1.14.9
    - rosclean==1.14.9
    - roscreate==1.14.9
    - rosgraph==1.14.13
    - roslaunch==1.14.13
    - roslib==1.14.9
    - roslint==0.11.2
    - roslz4==1.14.13
    - rosmake==1.14.9
    - rosmaster==1.14.13
    - rosmsg==1.14.13
    - rosnode==1.14.13
    - rosparam==1.14.13
    - rospy==1.14.13
    - rosserial_arduino==0.8.0
    - rosserial_client==0.8.0
    - rosserial_python==0.8.0
    - rosservice==1.14.13
    - rostest==1.14.13
    - rostopic==1.14.13
    - rosunit==1.14.9
    - roswtf==1.14.13
    - rqt-moveit==0.5.10
    - rqt-reconfigure==0.5.4
    - rqt-robot-monitor==0.5.14
    - rqt-rviz==0.7.0
    - rqt_action==0.4.9
    - rqt_bag==0.5.1
    - rqt_bag_plugins==0.5.1
    - rqt_console==0.4.9
    - rqt_dep==0.4.9
    - rqt_graph==0.4.11
    - rqt_gui==0.5.3
    - rqt_gui_py==0.5.3
    - rqt_image_view==0.4.16
    - rqt_launch==0.4.8
    - rqt_logger_level==0.4.8
    - rqt_msg==0.4.8
    - rqt_nav_view==0.5.7
    - rqt_plot==0.4.13
    - rqt_pose_view==0.5.8
    - rqt_publisher==0.4.8
    - rqt_py_common==0.5.3
    - rqt_py_console==0.4.8
    - rqt_robot_dashboard==0.5.7
    - rqt_robot_steering==0.5.10
    - rqt_runtime_monitor==0.5.7
    - rqt_service_caller==0.4.8
    - rqt_shell==0.4.9
    - rqt_srv==0.4.8
    - rqt_tf_tree==0.6.0
    - rqt_top==0.4.8
    - rqt_topic==0.4.11
    - rqt_web==0.4.8
    - ruamel.yaml==0.17.21
    - ruamel.yaml.clib==0.2.6
    - rviz==1.13.24
    - scikit-image==0.17.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - scs==3.2.0
    - send2trash==1.8.0
    - sensor-msgs==1.12.8
    - shapely==1.7.1
    - six==1.16.0
    - sklearn==0.0
    - smach==2.0.1
    - smach_ros==2.0.1
    - smclib==1.8.5
    - soft-renderer==1.0.0
    - srdfdom==0.5.2
    - tabulate==0.8.9
    - tensorboardx==2.5
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.6.0
    - tf==1.12.1
    - tf2_geometry_msgs==0.6.5
    - tf2_kdl==0.6.5
    - tf2_py==0.6.5
    - tf2_ros==0.6.5
    - tf_conversions==1.12.1
    - threadpoolctl==3.1.0
    - tifffile==2020.9.3
    - timm==0.4.12
    - tomli==1.2.3
    - topic_tools==1.14.13
    - torch==1.4.0
    - torchvision==0.5.0
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==4.3.3
    - traits==6.3.2
    - traitsui==7.3.1
    - trimesh==3.12.5
    - typed-ast==1.5.4
    - typing_extensions==4.1.1
    - urdfdom-py==0.4.6
    - urllib3==1.26.9
    - vtk==9.1.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - wslink==1.6.4
    - xacro==1.13.17
    - xmltodict==0.12.0
    - yacs==0.1.8
    - yapf==0.32.0
    - yarl==1.7.2
    - zipp==3.6.0
prefix: /home/sunh/miniconda3/envs/yolo

**Comment by pieris98** [comment]
Hey @sunhan1997 ,
For the custom packages (e.g. ros dependencies) did you use a meta-package e.g. ros-release? I'm going through the dependencies pip list one-by-one and it's difficult to find all these package versions on github.

**Comment by sunhan1997** [comment]
About the ros, you should install ros in your ubuntu system. As for the conda env, you can use pip install rospkg. If you just run this code, you can ignore the ros package. If you want to run this code with robot, you should install ros firstly. In addition, I upload a new version which use the pyrender（from bop_toolkit）replacing the opengl. And the new version code maybe more suitable, I have run it in my RTX 4090.

**Comment by pieris98** [comment]
Hey again @sunhan1997 ,
I was able to install all packages in the new commit version you uploaded.
However, now trying to run `test_without_detection.py` the error is that PyTorch version doesn't support the Ampere compute capability `sm86` (my card is RTX3060).

You said you ran this on your RTX4090 so maybe you forgot to update `requirements.txt`? 
Right now if I install all required packages I have `torch==1.10.1`. 

Also I had to manually resolve some incompatibilities of packages with `easy_dxnet` repo, which you recommend to download for faster runtime.

If you could provide any guidance or upload an up-to-date `requirements.txt` file (from conda env export/pip freeze) that would be very helpful.

Appreciate all your help on my issues!

**Comment by sunhan1997** [comment]
hello, the` requirements.txt` is  no  problem, and the pytorch is 1.10.1. You can try` conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge` to install the pytorch.  In addition, the `easy_dxnet` is not used in this project. I mean, in future work, the  `easy_dxnet` can be used to sample grasps for better performance.
